#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

setting='$base_url = '

[[  -z $BASE_URL ]] && echo "BASE_URL is not set" ||  echo "$setting " "'""$BASE_URL""';" >> /var/www/html/sites/default/settings.php

exec "$@"