services:
  mariadb:
    restart: unless-stopped
    image: stiahau/h5p-bildetema-mariadb:0.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

    # ports:
    #   - 3306:3306

  wordpress:
    depends_on:
      - mariadb
    image: stiahau/h5p-bildetema-wordpress:0.1.0
    restart: unless-stopped
    volumes:
      # WP-CONFIG
      - ./docker-config/wp-config.php:/var/www/html/wp-config.php

      # Bildetema
      - ./h5p-bildetema/dist/:/var/www/html/wp-content/uploads/h5p/libraries/H5P.Bildetema-1.0/dist/

      # Bildetema grid
      - ./h5p-bildetema-words-grid-view/dist/:/var/www/html/wp-content/uploads/h5p/libraries/H5P.BildetemaWordsGridView-1.0/dist/

      # Bildetema topic view
      - ./h5p-bildetema-words-topic-image/dist/:/var/www/html/wp-content/uploads/h5p/libraries/H5P.BildetemaTopicImageView-1.0/dist/

      # Bildetema editor
      - ./h5p-editor-bildetema-words-topic-image/dist/:/var/www/html/wp-content/uploads/h5p/libraries/H5PEditor.BildetemaWordsTopicImage-1.0/dist/

    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    ports:
      - 8090:80
