name: Check Licenses

on:
  - pull_request

jobs:
  check-license:
    name: Check license

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun and Install
        uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile

      - name: Check licenses
        run: bun run check-licenses
