name: Check Licenses

on:
  - pull_request

jobs:
  check-license:
    name: Check license

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1

      - name: Check licenses
        run: npm run check-licenses
