name: "Build and validate: h5p-bildetema-words-grid-view"

on:
  pull_request:
    paths:
      - common/**
      - h5p-bildetema-words-grid-view/**

  workflow_dispatch: {}

env:
  working-directory: "./h5p-bildetema-words-grid-view"

defaults:
  run:
    working-directory: "./h5p-bildetema-words-grid-view"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build
        working-directory: ${{env.working-directory}}

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.working-directory}}

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.working-directory}}

      - name: Test
        run: npm run test
        env:
          CI: true
