name: "Pack and release content type: h5p-bildetema-words-topic-image"

on:
  push:
    branches:
      - main
    paths:
      - common/**
      - h5p-bildetema-words-topic-image/**

  workflow_dispatch: {}

env:
  project-id: h5p-bildetema-words-topic-image

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    name: Pack and release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack .h5p file
        uses: boyum/pack-h5p-action@0.0.6
        id: release-h5p
        with:
          working-directory: ./${{env.project-id}}

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest # https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{env.project-id}}_${{steps.release-h5p.outputs.version}}
          prerelease: false
          files: |
            ${{steps.release-h5p.outputs.filePath}}
