name: Pack and release content type

on: [push, workflow_dispatch]

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    name: Pack and release
    steps:
      - uses: actions/checkout@v2
      - uses: boyum/pack-h5p-action@0.0.6
        id: release-h5p
      - uses: "marvinpinto/action-automatic-releases@latest" # https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{steps.release-h5p.outputs.version}}
          prerelease: false
          files: |
            ${{steps.release-h5p.outputs.filePath}}
